import { type NextPage } from "next";
import Head from "next/head";
import { UserButton } from "@clerk/nextjs";
import { api } from "~/utils/api";
import type { Snake } from "@prisma/client"
import Link from "next/link";

const Home: NextPage = () => {
  const { data } = api.snake.getAllSnakes.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex justify-between p-3 text-center items-center gap-3">
        <UserButton afterSignOutUrl="/" />
        <h1 className="font-extrabold text-2xl md:text-4xl">Snake meal tracker</h1>
        <div className="flex gap-2">
          <Link href="/new-snake">
            <button className='border-black border-2 bg-green-400 rounded-md p-3 text-white font-bold'>
              New snake
            </button>
          </Link>
          <Link href="/config">
            <button className='border-black border-2 bg-slate-400 rounded-md p-3 text-white font-bold'>
              Config
            </button>
          </Link>
        </div>
      </header>
      <main className="grid grid-cols-4 p-2 gap-2 text-center">
        {data?.snakes.length === 0 ? <div className="col-start-1 col-end-5 text-lg font-bold">No snakes in the list</div> : null}
        {data?.snakes?.map((snake: Snake) => {
          return <Link key={snake.id} href={`/snake/${snake.id}`} className="border-2 border-black rounded-md text-lg font-semibold">
            {snake.name}
          </Link>
        })}
      </main>
    </>
  );
};

export default Home;
