import { type NextPage } from "next";
import Head from "next/head";
import { UserButton } from "@clerk/nextjs";
import { api } from "~/utils/api";
import type {Snake} from "@prisma/client"
import Link from "next/link";

const Home: NextPage = () => {
  const {data} = api.snake.getAllSnakes.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex justify-between p-3">
        <UserButton afterSignOutUrl="/" />
        <button className="bg-green-400 rounded-md p-3 text-white font-bold">
        <Link href="/new-snake">New snake</Link>
        </button>
      </header>
      <main>

        {data?.snakes.length === 0 ? <p>No snakes in the list</p> : null}
        <div className="grid grid-cols-4 p-2 gap-2">
        {data?.snakes?.map((snake: Snake) => {
          return <Link key={snake.id} href={`/snake/${snake.id}`} className="border-2 border-black rounded-md">
            {snake.name}
          </Link>
        })}
        </div>
      </main>
    </>
  );
};

export default Home;
