import { type NextPage } from "next";
import Head from "next/head";
import { UserButton } from "@clerk/nextjs";
import { api } from "~/utils/api";
import type { Snake } from "@prisma/client";
import Link from "next/link";

const Home: NextPage = () => {
  const { data } = api.snake.getAllSnakes.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex items-center justify-between gap-3 p-3 text-center">
        <UserButton afterSignOutUrl="/" />
        <h1 className="text-2xl font-extrabold md:text-4xl">
          Snake meal tracker
        </h1>
        <div className="flex gap-2">
          <Link href="/new-snake">
            <button className="rounded-md border-2 border-black bg-green-400 p-3 font-bold text-white">
              New snake
            </button>
          </Link>
        </div>
      </header>
      <main className="grid grid-cols-4 gap-2 p-2 text-center">
        {data?.snakes.length === 0 ? (
          <div className="col-start-1 col-end-5 text-lg font-bold">
            No snakes in the list
          </div>
        ) : null}
        {data?.snakes?.map((snake: Snake) => {
          return (
            <Link
              key={snake.id}
              href={`/snake/${snake.id}`}
              className="rounded-md border-2 border-black text-lg font-semibold"
            >
              {snake.name}
            </Link>
          );
        })}
      </main>
    </>
  );
};

export default Home;
